name: Upload to GitHub
runs:
  using: composite
  steps:

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/
        merge-multiple: true # place all files into artifacts/ directly

    - name: Set GITHUB_RELEASE_TAG & ARTIFACT_ID
      shell: bash
      run: |
        set -eux
        if [[ '${{ github.ref }}' = refs/tags/ldc-v* ]]; then
          tag='${{ github.ref }}'
          tag="${tag:10}"
          artifactID="${tag:5}"
        else
          tag=CI
          artifactID='${{ github.sha }}'
          artifactID="${artifactID:0:8}"
        fi
        echo "GITHUB_RELEASE_TAG=$tag" >> $GITHUB_ENV
        echo "ARTIFACT_ID=$artifactID" >> $GITHUB_ENV

    - name: Download existing artifacts from GitHub release
      # only enabled for the upstream repo by default - (probably) needs an existing release
      if: github.repository == 'ldc-developers/llvm-project'
      # don't fail if there are no existing artifacts yet
      continue-on-error: true
      uses: dsaltares/fetch-gh-release-asset@1.1.1
      with:
        version: tags/${{ env.GITHUB_RELEASE_TAG }}
        regex: true
        # only those with matching ARTIFACT_ID
        file: ^llvm-${{ env.ARTIFACT_ID }}-
        target: existing-artifacts/

    - name: Merge existing artifacts & compute hashes
      shell: bash
      run: |
        set -eux

        cd artifacts

        # Extend by existing release artifacts *missing* from GitHub workflow,
        # e.g., artifacts published by Cirrus CI etc.
        # (They will be re-uploaded in the next step.)
        if [[ -d ../existing-artifacts ]]; then
          mv -n ../existing-artifacts/*.* ./
        fi

        ls -lh
        sha256sum * > "llvm-$ARTIFACT_ID.sha256sums.txt"

    - name: Upload to GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.GITHUB_RELEASE_TAG }}
        artifacts: artifacts/*
        allowUpdates: true
        artifactErrorsFailBuild: true
        prerelease: false
        omitPrereleaseDuringUpdate: true
        omitName: true
        omitBody: true
        omitDraftDuringUpdate: true
        # remove existing artifacts for 'CI' release
        #removeArtifacts: ${{ env.GITHUB_RELEASE_TAG == 'CI' }}
